services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    
  web:
    env_file:
      - .env
    build: .
    working_dir: /app  # Establecer el directorio de trabajo correcto
    command: > 
      sh -c "python manage.py esperar_a_db &&
             python manage.py makemigrations && 
             python manage.py migrate &&    
             python manage.py showmigrations &&  
             python manage.py runserver 0.0.0.0:8000"
      
    volumes:
      - ./app:/app  # Asegurar que la carpeta "app" se monta correctamente
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
