services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: contrasena
      POSTGRES_DB: objetos_perdidos_fca
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    working_dir: /app  # Establecer el directorio de trabajo correcto
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app  # Asegurar que la carpeta "app" se monta correctamente
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
