# Generated by Django 4.2.20 on 2025-03-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('facultad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Objetoperdido',
            fields=[
                ('id_objeto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_perdida', models.DateField()),
                ('lugar_perdida', models.CharField(max_length=255)),
                ('estado_objeto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'objetoperdido',
            },
        ),
        migrations.CreateModel(
            name='Trajano',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'trajano',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_institucional', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.TextField()),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reporteentrega',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_entrega', models.DateTimeField()),
                ('imagen_evidencia', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_objeto', models.ForeignKey(db_column='id_objeto', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.objetoperdido')),
                ('id_usuario_reclamante', models.ForeignKey(blank=True, db_column='id_usuario_reclamante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.usuario')),
            ],
            options={
                'db_table': 'reporteentrega',
            },
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='id_usuario_reclamante',
            field=models.ForeignKey(blank=True, db_column='id_usuario_reclamante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_notificacion', models.DateTimeField()),
                ('estado_lectura', models.BooleanField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Imagenobjeto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(max_length=255)),
                ('id_objeto', models.ForeignKey(blank=True, db_column='id_objeto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.objetoperdido')),
                ('id_reporte', models.ForeignKey(blank=True, db_column='id_reporte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.reporteentrega')),
            ],
            options={
                'db_table': 'imagenobjeto',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField()),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('id_objeto', models.ForeignKey(db_column='id_objeto', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.objetoperdido')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.usuario')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.carrera')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.usuario')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(max_length=20, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.usuario')),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
    ]
