# Generated by Django 4.2.21 on 2025-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(max_length=20, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('licenciatura', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField()),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenobjeto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'imagenobjeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_notificacion', models.DateTimeField()),
                ('estado_lectura', models.BooleanField()),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objetoperdido',
            fields=[
                ('id_objeto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_perdida', models.DateField()),
                ('lugar_perdida', models.CharField(max_length=255)),
                ('estado_objeto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'objetoperdido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporteentrega',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_entrega', models.DateTimeField()),
                ('imagen_evidencia', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporteentrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
