# Generated by Django 4.2.21 on 2025-05-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
