# Generated by Django 4.2.23 on 2025-06-23 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_historialadministrativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='imagenobjeto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='objetoperdido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reporteentrega',
            options={},
        ),
        migrations.AddField(
            model_name='historialadministrativo',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialadministrativo',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', default=51, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
