# Generated by Django 4.2.23 on 2025-06-23 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_administrador_options_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='num_empleado',
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', default=51, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', default=51, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_objeto',
            field=models.ForeignKey(db_column='id_objeto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.objetoperdido'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=51, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagenobjeto',
            name='id_objeto',
            field=models.ForeignKey(blank=True, db_column='id_objeto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.objetoperdido'),
        ),
        migrations.AddField(
            model_name='imagenobjeto',
            name='id_reporte',
            field=models.ForeignKey(blank=True, db_column='id_reporte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.reporteentrega'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=51, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='id_usuario_reclamante',
            field=models.ForeignKey(blank=True, db_column='id_usuario_reclamante', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporteentrega',
            name='id_objeto',
            field=models.ForeignKey(db_column='id_objeto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.objetoperdido'),
        ),
        migrations.AddField(
            model_name='reporteentrega',
            name='id_usuario_reclamante',
            field=models.ForeignKey(blank=True, db_column='id_usuario_reclamante', default=51, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
