# Generated by Django 4.2.23 on 2025-07-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_administrador_curp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoperdido',
            name='estado_objeto',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('publicado', 'Publicado'), ('reclamado', 'Reclamado'), ('entregado', 'Entregado'), ('no reclamado', 'No reclamado')], max_length=50),
        ),
    ]
