# Generated by Django 4.2.23 on 2025-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_objetoperdido_estado_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenobjeto',
            name='ruta_imagen',
            field=models.ImageField(upload_to='objetos/'),
        ),
        migrations.AlterModelTable(
            name='imagenobjeto',
            table='imagen_objeto',
        ),
        migrations.AlterModelTable(
            name='objetoperdido',
            table='objeto_perdido',
        ),
        migrations.AlterModelTable(
            name='reporteentrega',
            table='reporte_entrega',
        ),
    ]
