# Generated by Django 4.2.23 on 2025-07-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_imagenobjeto_ruta_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenobjeto',
            name='id_objeto',
            field=models.ForeignKey(blank=True, db_column='id_objeto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imagenes', to='apps.objetoperdido'),
        ),
        migrations.AlterModelTable(
            name='imagenobjeto',
            table='imagenobjeto',
        ),
        migrations.AlterModelTable(
            name='objetoperdido',
            table='objetoperdido',
        ),
        migrations.AlterModelTable(
            name='reporteentrega',
            table='reporteentrega',
        ),
    ]
