# Generated by Django 4.2.23 on 2025-07-22 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_imagenobjeto_id_objeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenobjeto',
            name='id_objeto',
            field=models.ForeignKey(blank=True, db_column='id_objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='apps.objetoperdido'),
        ),
    ]
