# Generated by Django 4.2.23 on 2025-07-28 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_imagenobjeto_id_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoperdido',
            name='fecha_carga',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
