# Generated by Django 4.2.23 on 2025-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_objetoperdido_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoperdido',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
