# Generated by Django 4.2.23 on 2025-08-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_objetoperdido_fecha_carga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetoperdido',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='descripcion_especifica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='descripcion_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='hora_perdida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='reportado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
