# Generated by Django 4.2.23 on 2025-08-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_objetoperdido_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetoperdido',
            old_name='reportado_por',
            new_name='encontrado_por',
        ),
    ]
