# Generated by Django 4.2.23 on 2025-08-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_rename_reportado_por_objetoperdido_encontrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoperdido',
            name='descripcion_especifica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objetoperdido',
            name='descripcion_general',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objetoperdido',
            name='encontrado_por',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objetoperdido',
            name='hora_perdida',
            field=models.TimeField(),
        ),
    ]
