# Generated by Django 4.2.23 on 2025-08-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_objetoperdido_descripcion_especifica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_edicion',
        ),
    ]
