# Generated by Django 4.2.23 on 2025-08-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_remove_comentario_fecha_edicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar_Perdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'lugar_perdida',
            },
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='id_lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos', to='apps.lugar_perdida'),
        ),
    ]
