# Generated by Django 4.2.23 on 2025-08-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_lugar_perdida_objetoperdido_id_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetoperdido',
            name='lugar_perdida',
        ),
    ]
